num1 = int(input("Enter your first number = "))
num2 = int(input("Enter your 2nd number = "))
print("Addition of numbers is = " , num1 + num2) 
print("Subtraction of numbers is = " , num1 - num2)
print("Multiplication of numbers is = " , num1 * num2)
print("Division of numbers is = " , num1 / num2)